#!/bin/sh
# bspwm startup

bspc config border_width 7
bspc config window_gap 20

bspc config split_ratio 0.5

bspc monitor eDP1 -d 1 2 3 4 5
bspc monitor DP1 -d  6 7 8 9 10

sxhkd &
~/.fehbg &
~/Code/shell_scripts/animated_wallpaper.sh
nm-applet &
blueman-applet &
light-locker &
~/.config/polybar/launch.sh
