#!/bin/sh
# bspwm startup

bspc config border_width 2
bspc config normal_border_color \#23252d
#bspc config active_border_color \#d1ddd1
bspc config focused_border_color \#99d5b8

bspc config window_gap 50
bspc config left_padding 50
bspc config right_padding 50
bspc config top_padding 20
bspc config bottom_padding 0

bspc config single_monocle true
bspc config gapless_monocle false
bspc config borderless_monocle true

bspc config split_ratio 0.5
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc monitor DP-0 -d 1 2 3 4 5
bspc monitor HDMI-0 -d 6 7 8 9 10

# game projects
bspc rule -a Vulkan state=floating
bspc rule -a vulkanExample,* state=floating
bspc rule -a Navigator, firefox state=floating
bspc rule -a origin.exe state=floating

#wal -ni ~/Pictures/snowy_mountains.jpg -a "80" -b "#1F1D19"
~/.fehbg &
~/.config/bspwm/init.sh
