#!/bin/sh

xrdb ~/.Xresources
xset r rate 270 60
xrandr --output DP-0 --primary --output HDMI-0 --above DP-0
xsetroot --cursor_name left_ptr
xsetroot -xcf /usr/share/icons/Adwaita/cursors/left_ptr 16

exec bspwm
